### ISSUE TITLE
The menu does nothing so it's not needed

### ISSUE THREAD

**Issue by LordLukin** [jzych/KursCPP-UniversityDB2#12]
https://github.com/jzych/KursCPP-UniversityDB2/blob/71fd945a4ce033dceebb4e2ebead870355b1191e/main.cpp#L49-L93

**Comment by jzych** [comment]
Resolved in https://github.com/jzych/KursCPP-UniversityDB2/commit/f94362388270a8b7abf3085c29102e6c91b1ec73
