### ISSUE TITLE
Search functions should return an iterator or a pointer

### ISSUE THREAD

**Issue by LordLukin** [jzych/KursCPP-UniversityDB2#14]
https://github.com/jzych/KursCPP-UniversityDB2/blob/71fd945a4ce033dceebb4e2ebead870355b1191e/includes/DataBase.hpp#L20-L21
We can assume, that when someone is searching for a person, he wants to do some operation on it. It would be great to have an iterator or a pointer, to allow calling some functions on a found person.

**Comment by jzych** [comment]
Resolved in https://github.com/jzych/KursCPP-UniversityDB2/commit/9aaa5db8a3bccfc20da0285339b278919b233936
