### ISSUE TITLE
Sorting lambdas have different parameters

### ISSUE THREAD

**Issue by LordLukin** [jzych/KursCPP-UniversityDB2#15]
https://github.com/jzych/KursCPP-UniversityDB2/blob/71fd945a4ce033dceebb4e2ebead870355b1191e/DataBase.cpp#L4
https://github.com/jzych/KursCPP-UniversityDB2/blob/71fd945a4ce033dceebb4e2ebead870355b1191e/DataBase.cpp#L18
https://github.com/jzych/KursCPP-UniversityDB2/blob/71fd945a4ce033dceebb4e2ebead870355b1191e/DataBase.cpp#L24
Both of these are coparators used in sort algorithm. It would be nice to have the same parameters.
I would even opt for `const auto` as a param in both cases. It's so generic :)

**Comment by jzych** [comment]
Resolved in https://github.com/jzych/KursCPP-UniversityDB2/commit/29cceefa5680e5a7b8da4c03e59f38040259f564

**Comment by jzych** [comment]
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4 compiler has return below error:
> error: parameter declared ‘auto’

**Comment by jzych** [comment]
Travis yml file has been modified.
