### ISSUE TITLE
In Employee class, income is an int, but uint is passed here.

### ISSUE THREAD

**Issue by LordLukin** [jzych/KursCPP-UniversityDB2#16]
https://github.com/jzych/KursCPP-UniversityDB2/blob/71fd945a4ce033dceebb4e2ebead870355b1191e/DataBase.cpp#L54

**Comment by jzych** [comment]
Resolved in https://github.com/jzych/KursCPP-UniversityDB2/commit/a441ea3584cb811023d37a82bb3ea76c762be2ef
