### ISSUE TITLE
Tabs instead of spaces in main.cpp

### ISSUE THREAD

**Issue by LordLukin** [jzych/KursCPP-UniversityDB2#2]
https://github.com/jzych/KursCPP-UniversityDB2/blob/5efe689a62147874e75a19fa4603841500c6c67d/main.cpp#L70

**Comment by jzych** [comment]
Issue resolved in commit:
https://github.com/jzych/KursCPP-UniversityDB2/commit/14a043b87082e2d25cd682d43695a832926903d6
