### ISSUE TITLE
Included headers

### ISSUE THREAD

**Issue by gitmajo** [jzych/KursCPP-UniversityDB2#22]
I am not 100% sure, so @LordLukin please verify me... 
Headers should be included to .hpp only if that file really need that header? Default place for header is cpp file. 

`#include <algorithm>
#include <fstream>`

https://github.com/jzych/KursCPP-UniversityDB2/blob/08ada8b1c22ffd764991336769755c50d2fff9b3/includes/DataBase.hpp#L4

based on: https://stackoverflow.com/a/16821899/9854242

**Comment by LordLukin** [comment]
That's true. If you don't use any fstream in hpp file, but you use it in cpp file, then the include should be in cpp file. 
Even if you have a pointer in hpp file to used data from the header, you still don't need the include. Class forward declaration is enough.

**Comment by jzych** [comment]
Resolved in https://github.com/jzych/KursCPP-UniversityDB2/commit/6750716b711f80483359b708b3b26fc73cf3432b
